// === Constant Buffers ===
cbuffer CameraConstants : register(b2)
{
    float4x4 WorldToCameraTransform;
    float4x4 CameraToRenderTransform;
    float4x4 RenderToClipTransform;
    float2 ViewportSize; 
    float2 _Padding;
}

cbuffer ModelConstants : register(b3)
{
    float4x4 ModelToWorldTransform;
    float4 ModelColor;
}

// === Vertex Shader Input ===
struct vs_input_t
{
    float3 position : POSITION;       // World position (not local!)
    uint colorPacked : COLOR;
    float2 uv : TEXCOORD;
    uint physicsType : PHYSICSTYPE;
    float emission : EMISSION;
};

// === Vertex to Pixel ===
struct v2p_t
{
    float4 position : SV_Position;
    float4 color : COLOR;
    float2 uv : TEXCOORD;
    uint physicsType : PHYSICSTYPE;  
    float emission : EMISSION;     
};

// === Helper: Unpack Color ===
float4 UnpackColor(uint packed)
{
    return float4(
        (packed & 0xFF) / 255.0,
        ((packed >> 8) & 0xFF) / 255.0,
        ((packed >> 16) & 0xFF) / 255.0,
        ((packed >> 24) & 0xFF) / 255.0
    );
}

// === Vertex Shader ===
v2p_t VertexMain(vs_input_t input)
{
    // Input position is already in world space (generated by compute shader)
    float4 worldPosition = float4(input.position.x,input.position.y,50.f, 1.0);
    
    // Transform through camera pipeline
    float4 camPosition = mul(WorldToCameraTransform, worldPosition);
    float4 renderPosition = mul(CameraToRenderTransform, camPosition);
    float4 clipPosition = mul(RenderToClipTransform, renderPosition);
    
    v2p_t output;
    output.position = clipPosition;
    output.color = UnpackColor(input.colorPacked);
    output.uv = input.uv;

    output.physicsType = input.physicsType; 
    output.emission = input.emission;      
    
    return output;
}

// === Pixel Shader Output (MRT) ===
struct PSOutput
{
    float4 color : SV_Target0;          // RT0
    float4 collision : SV_Target1;      // RT1 Collision Texture
    float4 bloom : SV_Target2;          // RT2 Bloom Texture
};

// === Pixel Shader ===
PSOutput PixelMain(v2p_t input)
{
    PSOutput output;
    
    // RT0: Main color for display
    output.color = input.color;
    
    // RT1: Collision texture (color-encoded physics type)
    // Encoding scheme:
    // PHY_EMPTY (0)               -> Black   (0, 0, 0, 0)
    // PHY_STATIC_SOLID (1)        -> Red     (1, 0, 0, 1)
    // PHY_MOVE_SOLID (2)          -> Yellow  (1, 1, 0, 1)  (sand-like)
    // PHY_LIQUID (3)              -> Blue    (0, 0, 1, 1)
    // PHY_CELLULAR_AUTOMATON (4+) -> Green   (0, 1, 0, 1)  (special)
    
    if (input.physicsType == 0)
    {
        output.collision = float4(0, 0, 0, 0);  // Empty (air)
    }
    else if (input.physicsType == 1)
    {
        output.collision = float4(1, 0, 0, 1);  // Static solid (red)
    }
    else if (input.physicsType == 2)
    {
        output.collision = float4(1, 1, 0, 1);  // Movable solid (yellow)
    }
    else if (input.physicsType == 3)
    {
        output.collision = float4(0, 0, 1, 1);  // Liquid (blue)
    }
    else  // physicsType >= 4
    {
        output.collision = float4(0, 1, 0, 1);  // Cellular automaton (green)
    }
    
    // RT2: Bloom texture (emissive objects only)
    if (input.emission > 0.0)
    {
        // Bloom color = base color × emission strength × multiplier
        output.bloom = input.color * input.emission * 2.0;
    }
    else
    {
        output.bloom = float4(0, 0, 0, 0);  // Non-emissive = black
    }
    
    return output;
}